# Generated by Django 5.2.7 on 2025-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestao_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='certificado_liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(help_text='Horário de término do evento no último dia.'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instituicao_ensino',
            field=models.CharField(blank=True, help_text='Instituição de ensino do usuário (obrigatório para Alunos e Professores)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.permission'),
        ),
    ]
